name: cactoos_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/Abd-ElRazek-Ali-Awad-Hassan/cactoos_dart

environment:
  sdk: ^3.7.2

dependencies:
  equatable: ^2.0.7
  rxdart: ^0.28.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  file: any
