name: cactoos_dart
description: Cactoos Dart is a collection of object-oriented primitives for Dart.
version: 2.0.1+0
repository: https://github.com/Abd-ElRazek-Ali-Awad-Hassan/cactoos_dart
license: MIT

environment:
  sdk: ^3.7.2

dependencies:
  equatable: ^2.0.7

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  file: any
